baseURL = ""
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "The Cornell Independent"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "https://www.thecornellindependent.com/contact"
name = "Contact"
url = "https://thecornellindependent.com/contact"
weight = 1
[[menu.desktop]]
URL = "https://www.thecornellindependent.com/about"
name = "About"
url = "https://thecornellindependent.com/about"
weight = 2
[[menu.main]]
URL = "https://www.thecornellindependent.com/contact"
name = "Contact"
url = "https://thecornellindependent.com/contact"
weight = 3
[[menu.main]]
URL = "https://www.thecornellindependent.com/about"
name = "About"
url = "https://thecornellindependent.com/about"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
# favicon
[params.favicon]
favicon = "favicon.ico"
[params]
author = "The Cornell Independent"
description = "The Cornell Independent is Cornell University’s premier news and opinion publication and blog."
images = ["/images/the-cornell-independent.png"]
title = "The Cornell Independent"
url = "https://www.thecornellindependent.com/"
[params.banner]
heading = "The Cornell Independent"
image = "/images/the-cornell-independent.png"
[params.blog]
heading = "Premier common sense insights from a strong, independent perspective"
[params.call_to_action]
button_label = "Contact Us"
button_url = "mailto:editor@thecornellindependent.com"
content = ""
enable = true
title = "Contact us for more information."
[params.footer]
address = "Ithaca, NY 14850"
content = ""
copyright = "The Cornell Independent Copyright &copy; 2022"
hours = "N/A"
title = "The Cornell Independent"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
series = "series"
tag = "tags"
