baseURL = ""
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "The Cornell Progressive"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
name = "About"
url = "https://www.thecornellprogressive.com/about"
weight = 2
[[menu.desktop]]
URL = "contact"
name = "Contact"
url = "https://www.thecornellprogressive.com/contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
url = "https://www.thecornellprogressive.com/contact"
weight = 3
[[menu.main]]
URL = "about"
name = "About"
url = "https://thecornellprogressive.com/about"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "The Cornell Progressive"
description = "This is meta description"
[params.banner]
heading = "The Cornell Progressive"
image = "/images/add-a-heading.png"
[params.blog]
heading = "The premier destination for Progressive insights since 2004."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = ""
enable = false
title = "Contact us for more information."
[params.footer]
address = ""
content = ""
copyright = "The Cornell Progressive Copyright &copy; 2021"
hours = ""
title = "The Cornell Progressive"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "editor@thecornellprogressive.com"
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
